### ISSUE TITLE
Scrobbler not working

### ISSUE THREAD

**Issue by everlyy** [kawaiiDango/pano-scrobbler#410]
**Describe the bug**
Scrobbler is not reacting to any music app playing anything, no notifications but also no errors in the UI. I have reinstalled the app, it worked for a few days but then it broke again.

**Steps to Reproduce**
I don't have anything specific, it just randomly didn't work anymore.

**App version**
v 3.17 - 2024, Jan 31

**Additional info**
I hooked up my phone to my computer and looked at `logcat` and saw an error from the scrobbler:
```
02-06 10:57:14.034 15586 15586 W scrobbler: isScrobblerRunning : service not running
02-06 10:57:14.037 15586 15586 W scrobbler: java.lang.Exception: bgScrobbler not running
02-06 10:57:14.037 15586 15586 W scrobbler:     at com.arn.scrobble.MainActivity.y(SourceFile:142)
02-06 10:57:14.037 15586 15586 W scrobbler:     at com.arn.scrobble.z1.o(SourceFile:1)
02-06 10:57:14.037 15586 15586 W scrobbler:     at p4.a.l(SourceFile:9)
02-06 10:57:14.037 15586 15586 W scrobbler:     at kotlinx.coroutines.I.Y(SourceFile:51)
02-06 10:57:14.037 15586 15586 W scrobbler:     at kotlinx.coroutines.k.q(SourceFile:100)
02-06 10:57:14.037 15586 15586 W scrobbler:     at kotlinx.coroutines.k.F(SourceFile:33)
02-06 10:57:14.037 15586 15586 W scrobbler:     at kotlinx.coroutines.k.r(SourceFile:26)
02-06 10:57:14.037 15586 15586 W scrobbler:     at androidx.fragment.app.A.run(SourceFile:64)
02-06 10:57:14.037 15586 15586 W scrobbler:     at android.os.Handler.handleCallback(Handler.java:938)
02-06 10:57:14.037 15586 15586 W scrobbler:     at android.os.Handler.dispatchMessage(Handler.java:99)
02-06 10:57:14.037 15586 15586 W scrobbler:     at android.os.Looper.loopOnce(Looper.java:210)
02-06 10:57:14.037 15586 15586 W scrobbler:     at android.os.Looper.loop(Looper.java:299)
02-06 10:57:14.037 15586 15586 W scrobbler:     at android.app.ActivityThread.main(ActivityThread.java:8293)
02-06 10:57:14.037 15586 15586 W scrobbler:     at java.lang.reflect.Method.invoke(Native Method)
02-06 10:57:14.037 15586 15586 W scrobbler:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
02-06 10:57:14.037 15586 15586 W scrobbler:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

It seems like the background scrobbler is not running, but I don't know how to fix that myself.

MIUI version: MIUI Global 14.0.1 Stable
Android: 12 SKQ1.211006.001

I've followed the steps on [don't kill my app](https://dontkillmyapp.com/xiaomi), to no success.

Thanks in advance!

**Comment by kawaiiDango** [comment]
This is not an issue with the app but with how some ROMs such as miui manage and kill background processes. The "kill reason" text on the bottom dialog or on a bug report email usually says what killed the app.
